require:
  - rubocop-performance
  - rubocop-rspec

AllCopd:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Layout/LineLength:
  Exclude:
    - spec/**/*.rb

Style/Documentation:
  Enabled: false

Rspec/MultipleExpectations:
  Max: 10